title: Climate Justice Montreal
title-fr: Justice climatique Montréal
keywords: climate, justice, indigenous, organize, resistance, solidarity, land defender
short_title: Climate Justice
short_title-fr: Justice climatique
email: 
myurl: https://cjm.summerhays.net
# myurl: localhost:4000

# This sets the point at which the website will switch from "desktop view" to "mobile/tablet view"
breakpoint: 1080px
verynarrow: 345px

webrick:
  headers:
    Cache-Control: max-age=31536000

# Certain types of media can be assigned to specific pages using this list. Everything in "media" is in the _include folder.

media_pages:
  - page_trans: quebec
    media: youtube/yt_embed.html
  - page_trans: calendar
    media: calendar.html
    media2: calendar2.html
  - page_trans: sandbox
    media: slideshow.html

    # Turn alerts on and off using this variable below. 
    # If you want alerts on all pages on the website, set 'alerts: all'.
    # If you want alerts on only certain pages, (the ones listed under "alert_pages"), set "alerts: some" 
      # Then put "- page_trans:" for each page an alert should appear under
    # Anything else, like '"alerton = "off"' and alerts will be off.
    # Change alert colour in the _sass/_colors.scss, $alert-color

redalerts: off
redalert_en-text: alert/en-covid.md
redalert_fr-text: alert/fr-covid.md
redalert_pages:
  - page_trans: index

greenalerts: off
greenalert_en-text: alert/en-midweek_over.md
greenalert_fr-text: alert/fr-midweek_over.md
greenalert_pages:
  - page_trans: index

    #This section allows you to easily control which pages will have which bird and text animation
bird_left: 
  - animation: land_left_flip
    trans: index
  - animation: roll_bird1
    trans: links_history
  - animation: swing-in1
    trans: index

bird_right:
  - animation: land_right
    trans: south_shore
  - animation: roll_bird2
    trans: quebec
  - animation: swing-in1
    trans: laurentians

mobile_bird: 
  - animation: swing-in1
    trans: index

    # the text at the top of each page on wide screens
header_animation:
  - animation: flicker-glow
    trans: quebec
  - animation: swing-in1
    trans: index
  - animation: focustext
    trans: quebec

    # the text at the top of each page on mobile/narrow screens
mobile_header_animation:
  - animation: flicker-glow
    trans: contribution

markdown: kramdown
include: ['_pages',".htaccess"]
exclude: ["backup","notes","Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"] 
sass:
  sass_dir: ./_sass
  style: compressed
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html,search-fr.html]
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/PDF"
    values:
      PDF: true
  - scope:
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename"
  - scope:
      path: "new_attender" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "nouveau" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "glossary" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

